services:
  - type: web
    name: unipulse-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        value: mongodb+srv://unipulse-user:123456Aa@unipulse-cluster.mdbj9db.mongodb.net/unipulse?retryWrites=true&w=majority&appName=unipulse-cluster
      - key: CLIENT_URL
        value: https://your-frontend.onrender.com