services:
  - type: web
    name: unipulse-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        value: your_mongodb_connection_string_here
      - key: CLIENT_URL
        value: https://your-frontend.onrender.com