version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unipulse
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/unipulse"
      JWT_SECRET: "replace_this_with_a_strong_secret"
      JWT_EXPIRES_IN: "1h"
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: sh -c "npm run prisma:generate && npm run prisma:migrate && npm run dev"

volumes:
  db-data: